language: erlang

before_script:
  - export GS_HOME="$(pwd)"
  - export PATH=$GS_HOME/bin:$PATH
  - export GS_TRAVIS=true
  - sudo apt-get update -qq
#  - sudo apt-get install ia32-libs
  - sudo apt-get -y install libpam0g:i386
  - sudo ln -s /lib/i386-linux-gnu/libpam.so.0 /lib/libpam.so.0

script:
  - bash installServer travis 3.2.1
  
