language: bash

before_script:
  - export BASE_PATH="$(pwd)"
  - cd gsDevKitHome
  - git checkout -b dev
  - export GS_HOME="$(pwd)"
  - export PATH=$GS_HOME/bin:$PATH

script:
  - bash installServer travis 3.2.1
