#! /bin/bash

#=========================================================================
# Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#
# Create project entry template script.
# 
#  1. Copy this file to the $GS_HOME/projects/<project=name> directory
#  2. Edit the following three shell variables as needed
#  3. Edit the project entry creation script to match the load specs for
#     your project
#  4. Implement your own helpOpts for additional options
#  5. Expand usage() as needed
#  
#=========================================================================

projectName="Seasid3"
projectDirectoryName="seaside3"
projectName="XXXHTTPComponents"
projectDirectoryName="XXX"
logFile="projectLoad_${projectName}.log"

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <stone-name> [<group-name> ... ]

Create project entry node for $projectName in tODE /home for named stone.

With no <group-name> specified, the Development group is loaded. It is highly
recommended that you choose one or more web adaptors:

  - Zinc
  - FastCGI
  - Swazoo

If you are just getting started, I recommend that you choose the Zinc web adaptor
and the Examples group.

OPTIONS
  -h show usage

EXAMPLES
  $(basename $0) -h
  $(basename $0) devkit Examples Zinc

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi
source ${GS_HOME}/bin/shFunctions

getOpts_help #parse standard (-h) options

if [ $# -ne 1 ]; then
  usage; exit 0
fi
stoneName="$1"
$GS_HOME/bin/tode serverDoIt $stoneName 1> $GS_HOME/gemstone/stones/$stoneName/logs/$logFile << EOF
  | entry result |
  entry := TDProjectSpecEntryDefinition new
    configuration: '${projectName}'
      version: '3.1.2'
      repository: 'http://www.smalltalkhub.com/mc/Seaside/MetacelloConfigurations/main'
      loads: #('Development' 'Examples' 'Zinc' 'FastCGI' 'Swazoo');
    status: #(#'active');
    yourself.
  result := entry createProjectEntryNode: '/home/${projectDirectoryName}'.
  ^result printString
EOF
